---
EnableDefaultLinters: true
glob: "**/*.{html,text,js}{+*,}.erb"
linters:
  ClosingErbTagIndent	:
    # Annoying based on how we write things
    enabled: false
  CommentSyntax:
    enabled: true
  ExtraNewline:
    enabled: true
  FinalNewline:
    enabled: true
  ParserErrors:
    enabled: true
  SelfClosingTag:
    # Jason no likey
    enabled: false
  SpaceAroundErbTag:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
  TrailingWhitespace:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Layout/HashAlignment:
        EnforcedLastArgumentHashStyle: ignore_implicit
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Style/MethodCallWithArgsParentheses:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false